- icon: "bar-chart"
  title: "Pre-approvals"
  description: "A comprehensive look at how much home you can afford."

- icon: "home"
  title: "Purchases"
  description: "Financing for first time or repeat home purchases."

- icon: "key"
  title: "Refinancing"
  description: "Take advantage of current interst rates or clawback equity with a refinance."

- icon: "refresh-circle"
  title: "Renewals"
  description: "Find the best option when your current mortgage term ends."

- icon: "contract"
  title: "Debt Consolidation"
  description: "Lower your total debt payments by cosolidating other debts into your mortgage."

- icon: "construct"
  title: "Building & Renovations"
  description: "Build a new home or get funds to renovate your existing home."